### PR TITLE
Updating the tutorials Part 1 to 4

### PR DESCRIPTION
**Pull request by VarLad**
Tutorials for Yao!

### CODE REVIEW

**Comment by GiggleLiu** [comment]
Thanks for the PR, the error happens elsewhere, no worries.

The Pluto notebooks should be put in a new folder, such as `notebooks`. I will review these notebooks ASAP.

Thanks again.

**Comment by GiggleLiu** [comment]
I read through your tutorial with interest, you even add an introduction to quantum physics! I like the idea of writing tutorials as Pluto notebooks so that the codes are guaranteed to work. I have several general comments,

1. The headings should be more consistently, because in the future, it might be compiled to the documentation page, then `<h1>` will appear in the "Table of contents". So, making headings correct would be very important. And please do not use Italic fonts in headings, also for consistency.

2. I don't think you need to hide the code blocks when you introduce the gates in p2.

2. In p3 and p4, I suggest not putting `##` before codes. I understand that want to make some assignment to make it interactive. Considering users might read the notebooks in different ways, I don't think it will work as you expected. You can put assignments at the end of the notebook. And I suggest using the following "test driven" form to make it fun.
Make the following cell not error
```julia
let
    circuit = ...;
    @test zero_state(2) |> circuit == ...
end
```
We can write helper blocks in Pluto notebooks, only if user click show result, it shows the results.
e.g. using the following autohide function
```julia
function autohide(ans)
	HTML("""
<a id="showans" href="javascript:void(0)">show/hide answer</button>
<div class="ans" style="display:none;">$(html(ans))</div>
<script>
const selector = this.querySelector("a");
const x = this.querySelector(".ans");
selector.onclick = () => {
	if (x.style.display === "none") {
		x.style.display = "block";
	} else {
		x.style.display = "none";
	}
};
</script>
""")
end;
```
and
```julia
md"""
    ```julia
    @test x == 3
    ```
""" |> autohide
```


To update, just commit and push to your own branch. Github will update automatically for you.

**Comment by GiggleLiu** [comment]
I have fixed the master branch. Please merge master with
```bash
$  git merge origin master
```

Then the build should pass.

**Comment by VarLad** [comment]
Thanks! I've been making a few minor changes here and there, based on the comments!
I'll push the new notebooks soon!

**Comment by VarLad** [comment]
Removed the self-do blocks
Instead it now has an assignment sheet named a1.jl. It also has a self check mechanism, which checks if your code is right or wrong and displays it to the reader/solver.

**Comment by VarLad** [comment]
Also... 
git merge origin master
shows "already up to date"

Edit: never mind, it has passed

**Comment by GiggleLiu** [comment]
Good. Thanks for the update. The `notebooks` folder should not be in the `assets` folder, it is not for this purpose.
You can just put it in the top level.

Also, since Pluto notebooks currently can not be compiled to HTML directly, you may want to add some introduction in the `README` to redirect users to these notebooks.

After fixing these issues, it should be ok to merge.

**Comment by clad26** [comment]
For readme.md

In the readme.md for tutorials, I can add this just before the License## Using Notebooks

You can use the Pluto Notebooks to learn the basics of Quantum Computing and Yao too. The prefered way to open the notebooks is by Opening them in Pluto in your system. Furthur information in [Notebook Folder](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks).
For any question or discussion, or if you spot an error, consider writing in the [Julia slack](https://slackinvite.julialang.org/) quantum-computing channel.

And then in the Notebook/README.md

Install [Pluto](https://github.com/fonsp/Pluto.jl) by running the following command in julia
```
]add Pluto
```
To run Pluto
```
import Pluto
Pluto.run()
```
Now you can either clone or download the repository and open the notebooks from the Notebooks folder in Pluto, or you can paste the link from the table of contents. 

### Table of contents
[Chapter 1](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks/p1.jl)
[Chapter 2](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks/p2.jl)
[Chapter 3](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks/p3.jl)
[Chapter 4](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks/p4.jl)
[Assignment 1](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks/a1.jl)

**Comment by VarLad** [comment]
For readme.md

In the readme.md for tutorials, I can add this just before the License

## Using Notebooks

You can use the Pluto Notebooks to learn the basics of Quantum Computing and Yao too. The prefered way to open the notebooks is by Opening them in Pluto in your system. Furthur information in [Notebook](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks) folder.
For any question or discussion, or if you spot an error, consider writing in the [Julia slack](https://slackinvite.julialang.org/) quantum-computing channel.

And then in the Notebook/README.md

Install [Pluto](https://github.com/fonsp/Pluto.jl) by running the following command in julia
```
]add Pluto
```
To run Pluto
```
import Pluto
Pluto.run()
```
Now you can either clone or download the repository and open the notebooks from the Notebooks folder in Pluto, or you can paste the link from the table of contents. 

### Table of contents
[1 - Introduction](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks/p1.jl)
- Who should read this tutorial
- Quantum 
- Bits

[2 - Working with Qubits](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks/p2.jl)
- Qubits
- Quantum Gates and Circuits
- Single Qubit Gates
- Multiqubit Gates

[3 - Using Yao](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks/p3.jl)
- Basics of building a circuit in Julia using Yao

[4 - Applications](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks/p4.jl)
- Bell Circuit, Reverse Bell Circuit and Bell State
- Superdense Coding
- Quantum Teleportation

[Assignment 1](https://github.com/QuantumBFS/tutorials/tree/master/Notebooks/a1.jl)

How about this? If this is acceptable, I'll push it immediately.

**Comment by GiggleLiu** [comment]
That looks perfect!

**Comment by VarLad** [comment]
> That looks perfect!

Pushed it!!!

**Pull request merged**
